### ISSUE TITLE
Drop sheet columns that can be added as part of post-processing step

### ISSUE THREAD

**Issue by attwad** [outbreakprepared/mvp-notes-and-ideas#10]
We will be dropping (from the Sheets, not the final CSV) : latitude, longitude, geo_resolution, location, admin3, admin2, admin1, country_new, admin_id.
We will be dropping from both sheets and CSV: wuhan(0)_not_wuhan(1).

Let's think a bit more about data_moderator_initials (it’s mostly empty), if we want to give some feedback perhaps (or if all errors come from the same person), I don't think it belongs in the final csv though.

**Comment by attwad** [comment]
@tbrewer-healthmap question related to #21 : does ID has to be part of the csv output? If so why?

**Comment by tbrewer-healthmap** [comment]
I think its' best to keep the ID as part of the CSV output, mostly because I think the final output should keep the same format in case anything is depending on that, also the map script keeps the IDs when generating a certain file that we send to an S3.

I also think its good to keep it to differentiate between the different sheets. That way if we see an issue there we know where to look.  

That being said, if you think its causing too many problems I'm open to debating it.

**Comment by attwad** [comment]
I haven't dropped the columns from the sheets yet, doing this now.
