### ISSUE TITLE
Figure out who consumes the current latest_output.csv and if anybody consumes the sheets directly

### ISSUE THREAD

**Issue by attwad** [outbreakprepared/mvp-notes-and-ideas#9]
To support potential refactorings of the sheets and make them snappier, we'd like to remove empty columns/move the geocoding stuff out but we don't know if anybody is reading from the sheets directly besides the scripts that we have.
Can somebody from the healthmap team shine a light on this please?
Thank you

**Comment by tbrewer-healthmap** [comment]
I don't' know who is currently using the latestdata.csv.  I can try to gather some info on that, but I the idea is to make it Public, so that anyone who wants to use it can.   So I'm all for simplifying it =) 

As for the reading the sheets, our scripts should be the only ones doing that. 

update on latestdata.csv users :
Mainly modeling groups : 
Modelling groups at: Institute for Disease modelling in Seattle, London School of Hygiene Tropical Medicine, Imperial College London, IHME Seattle, University of Hong Kong.

 and some general users we don't keep track of.

**Comment by sratcliffe118** [comment]
What we are looking for here is the key use cases that the data is enabling, who is best to speak to for this insight?

**Comment by tbrewer-healthmap** [comment]
> What we are looking for here is the key use cases that the data is enabling, who is best to speak to for this insight?

I would say Moritz is the best person to speak to about outside usage of the data.

**Comment by sratcliffe118** [comment]
Great, I will connect with him

**Comment by attwad** [comment]
We clarified that nothing except the map script was reading the sheets directly, the generated csv has the same columns as before. Only the columns in the sheets were dropped, I'm not sure if there's any follow-up needed here?
(What columns would be great to have in the consumable csv should be thought as part of the mid-long term plan, not for the current quick fixes imo).
wdyt?

**Comment by sratcliffe118** [comment]
What about the S3 data set does that also have the columns for geo location?

**Comment by tbrewer-healthmap** [comment]
The S3 data is a copy of the the full-data.json in the map pipeline : https://www.dropbox.com/s/t48xylj81vaw25g/full-data.json
That data is generated by reading the "latestdata.csv", filtering out US cases, and using the JHU data to fill them back in. So as long as the "latestdata.csv" keeps the same format (and the JHU), nothing should break in the pipeline
For the map pipeline/full-data generation you can look here : 
https://github.com/beoutbreakprepared/COVID-19-data-mapping-pipeline/blob/dev/scripts/pipeline.py

**Comment by sratcliffe118** [comment]
ok if nothing breaks this LGTM
